/*
 * Pins.h
 *
 * Created: 9/4/2018 6:30:33 AM
 *  Author: swain
 */ 


#ifndef PINS_H_
#define PINS_H_

#include "Header.h"

#define KEYDDR DDRC
#define KEYP PORTC
#define KEY11 PINC
#define KEYCC PINA
#define KEYA PINA6
#define KEYB PINA4
#define KEYC PINA2
#define KEYD PINA0
#define KEY1 PINC1
#define KEY2 PINC3
#define KEY3 PINC5
#define KEY4 PINC7

//LEDS

#define TS_LOW_PORT PORTL
#define TS_LOW_PIN PINL4

#define TS_HIGH_PORT PORTL
#define TS_HIGH_PIN PINL2

#define RH_LOW_PORT PORTG
#define RH_LOW_PIN PING2

#define RH_HIGH_PORT PORTG
#define RH_HIGH_PIN PING2

#define TA_LOW_PORT PORTL
#define TA_LOW_PIN PINL6

#define TA_HIGH_PORT PORTG
#define TA_HIGH_PIN PING0

#define TIMER_RUNNING_LED_PORT PORTA
#define TIMER_RUNNING_LED_PIN PINA3

#define DOOR_CLOSED_LED_PORT PORTA
#define DOOR_CLOSED_LED_PIN PINA5

#define TIMER_STOP_LED_PORT PORTA
#define TIMER_STOP_LED_PIN PINA1

#define KEYPAD_ENABLE_LED_PORT PORTC
#define KEYPAD_ENABLE_LED_PIN PINC0

#define SYSTEM_FAULT_LED_PORT PORTC
#define SYSTEM_FAULT_LED_PIN PINC4

#define FAN_ON_LED_PORT PORTA
#define FAN_ON_LED_PIN PINA7

#define HEATER_ON_LED_PORT PORTC
#define HEATER_ON_LED_PIN PINC6

/** BUTTONS */

#define START_PHOTO_BUTTON_PORT PINF
#define START_PHOTO_BUTTON_PIN 7

#define STOP_PHOTO_BUTTON_PORT PINK
#define STOP_PHOTO_BUTTON_PIN 0

#define START_INCUBATOR_BUTTON_PORT PINF
#define START_INCUBATOR_BUTTON_PIN 5

#define STOP_INCUBATOR_BUTTON_PORT PINF
#define STOP_INCUBATOR_BUTTON_PIN 6

#define RESET_BUTTON_PORT PINK
#define RESET_BUTTON_PIN 1

#define LIMIT_SWITCH_1_PORT PINK
#define LIMIT_SWITCH_1_PIN 2

#define LIMIT_SWITCH_2_PORT PINK
#define LIMIT_SWITCH_2_PIN 3

#define KEYPAD_BUTTON_PORT PINK
#define KEYPAD_BUTTON_PIN 4

#define POT 0
#define LM35_1 1
#define LM35_2 3
#define HUMIDITY 2

#define DDR(x) (*(&x - 1))      /* address of data direction register of port x */


#define FAN_PORT PORTB
#define FAN_PIN PINB7

#define HEATER_PORT PORTB
#define HEATER_PIN PINB4

#define PHOTO_PORT PORTB
#define PHOTO_PIN PINB6

#define PHOTO_PWM_PORT PORTB
#define PHOTO_PWM_PIN PINB5









#endif /* PINS_H_ */